# === Публікуємо теку frontend ===
[build]
  publish = "frontend"

# === Проксі усіх /api/* на Render-бекенд ===
# Після деплою на Render ЗАМІНИ домен нижче на твій onrender.com
[[redirects]]
  from = "/api/*"
  to   = "https://designer-shifttime.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
