import {pool,getDatabaseDiagnostics} from '../src/db.mjs';
import {getMigrationStatus01080} from '../src/migration-service.mjs';
const required=['platform_users','platform_accounts','platform_workspaces','platform_stores','platform_memberships','api_sessions','commerce_store_snapshots','commerce_outbox','marketplace_networks','marketplace_categories','marketplace_seller_profiles','marketplace_seller_offers','marketplace_listings','marketplace_carts','marketplace_cart_items','marketplace_orders','marketplace_seller_orders','marketplace_order_items','marketplace_payments','marketplace_payment_allocations','marketplace_inventory_reservations','marketplace_inventory_reservation_items','marketplace_inventory_ledger','marketplace_seller_order_deliveries','marketplace_shipping_events','platform_deployment_state','commerce_store_imports','commerce_import_rollbacks','media_cloud_assets','media_asset_derivatives','media_asset_events','shifttime_tables','shifttime_table_fields','shifttime_table_records','shifttime_table_views','shifttime_table_permissions','shifttime_table_templates','shifttime_published_sites','shifttime_site_deployments','shifttime_notification_receipts','shifttime_customer_messages','shifttime_notification_rules','shifttime_customer_message_thread','shifttime_ai_consultants','shifttime_ai_consultant_sessions','shifttime_ai_consultant_turns','shifttime_ai_consultant_sales_rules','shifttime_ai_consultant_offers','shifttime_schema_migrations'];
const checks=[];function add(name,ok,detail){checks.push({name,ok:Boolean(ok),detail});}
try{
  const db=await getDatabaseDiagnostics();const mig=await getMigrationStatus01080();add('migration-checksums',!mig.some(x=>x.applied&&!x.checksumMatch),mig.filter(x=>x.applied&&!x.checksumMatch).map(x=>x.filename));add('migration-pending',!mig.some(x=>!x.applied),mig.filter(x=>!x.applied).map(x=>x.filename));
  const tables=await pool.query(`SELECT table_name FROM information_schema.tables WHERE table_schema='public'`);const have=new Set(tables.rows.map(x=>x.table_name));add('required-tables',required.every(x=>have.has(x)),required.filter(x=>!have.has(x)));
  const snapshot=await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER (WHERE snapshot->>'schemaId'='shifttime-marketplace-schema-v1')::int valid FROM commerce_store_snapshots`);add('snapshot-schema',snapshot.rows[0].total===snapshot.rows[0].valid,snapshot.rows[0]);
  const scope=await pool.query(`SELECT COUNT(*)::int bad FROM platform_stores st LEFT JOIN platform_workspaces ws ON ws.id=st.workspace_id LEFT JOIN platform_accounts a ON a.id=ws.account_id WHERE ws.id IS NULL OR a.id IS NULL`);add('store-scope-integrity',scope.rows[0].bad===0,scope.rows[0]);
  const seller=await pool.query(`SELECT COUNT(*)::int bad FROM marketplace_seller_profiles sp LEFT JOIN platform_stores st ON st.id=sp.store_id WHERE st.id IS NULL`);add('seller-store-integrity',seller.rows[0].bad===0,seller.rows[0]);
  const order=await pool.query(`SELECT COUNT(*)::int bad FROM marketplace_seller_orders so LEFT JOIN marketplace_orders mo ON mo.id=so.marketplace_order_id LEFT JOIN platform_stores st ON st.id=so.store_id WHERE mo.id IS NULL OR st.id IS NULL`);add('seller-order-scope-integrity',order.rows[0].bad===0,order.rows[0]);
  const media=await pool.query(`SELECT COUNT(*)::int bad FROM media_cloud_assets a LEFT JOIN platform_stores st ON st.id=a.store_id LEFT JOIN platform_workspaces ws ON ws.id=a.workspace_id LEFT JOIN platform_accounts ac ON ac.id=a.account_id WHERE st.id IS NULL OR ws.id IS NULL OR ac.id IS NULL OR st.workspace_id<>a.workspace_id OR ws.account_id<>a.account_id`);add('media-asset-scope-integrity',media.rows[0].bad===0,media.rows[0]);
  const tableScope=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_tables t LEFT JOIN platform_accounts a ON a.id=t.account_id LEFT JOIN platform_workspaces w ON w.id=t.workspace_id LEFT JOIN platform_stores s ON s.id=t.store_id WHERE (t.scope_type='account' AND a.id IS NULL) OR (t.scope_type='workspace' AND (a.id IS NULL OR w.id IS NULL OR w.account_id<>t.account_id)) OR (t.scope_type='store' AND (a.id IS NULL OR w.id IS NULL OR s.id IS NULL OR w.account_id<>t.account_id OR s.workspace_id<>t.workspace_id))`);add('tables-scope-integrity',tableScope.rows[0].bad===0,tableScope.rows[0]);
  const aiConsultantScope=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_ai_consultants c LEFT JOIN shifttime_builder_sites bs ON bs.id=c.site_id WHERE bs.id IS NULL OR bs.account_id<>c.account_id OR bs.workspace_id<>c.workspace_id OR bs.store_id<>c.store_id`);add('ai-consultant-scope-integrity-01411',aiConsultantScope.rows[0].bad===0,aiConsultantScope.rows[0]);
  const aiConversationScope=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_ai_consultant_sessions s LEFT JOIN shifttime_ai_consultants c ON c.id=s.consultant_id LEFT JOIN shifttime_builder_sites bs ON bs.id=s.site_id WHERE c.id IS NULL OR bs.id IS NULL OR c.account_id<>s.account_id OR c.workspace_id<>s.workspace_id OR c.store_id<>s.store_id OR c.site_id<>s.site_id OR bs.account_id<>s.account_id OR bs.workspace_id<>s.workspace_id OR bs.store_id<>s.store_id`);add('ai-consultant-conversation-scope-01413',aiConversationScope.rows[0].bad===0,aiConversationScope.rows[0]);
  const aiPublicSessions=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_ai_consultant_sessions WHERE channel='site-runtime' AND COALESCE(context->>'publicVisitorHash','')=''`);add('ai-consultant-public-session-owner-01414',aiPublicSessions.rows[0].bad===0,aiPublicSessions.rows[0]);
  const aiSalesScope=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_ai_consultant_sales_rules r LEFT JOIN shifttime_ai_consultants c ON c.id=r.consultant_id LEFT JOIN shifttime_builder_sites bs ON bs.id=r.site_id WHERE c.id IS NULL OR bs.id IS NULL OR c.account_id<>r.account_id OR c.workspace_id<>r.workspace_id OR c.store_id<>r.store_id OR c.site_id<>r.site_id OR bs.account_id<>r.account_id OR bs.workspace_id<>r.workspace_id OR bs.store_id<>r.store_id`);add('ai-consultant-sales-rules-scope-01415',aiSalesScope.rows[0].bad===0,aiSalesScope.rows[0]);
  const aiOfferScope=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_ai_consultant_offers o LEFT JOIN shifttime_ai_consultants c ON c.id=o.consultant_id LEFT JOIN shifttime_ai_consultant_sessions s ON s.id=o.session_id LEFT JOIN shifttime_builder_sites bs ON bs.id=o.site_id WHERE c.id IS NULL OR s.id IS NULL OR bs.id IS NULL OR c.account_id<>o.account_id OR c.workspace_id<>o.workspace_id OR c.store_id<>o.store_id OR c.site_id<>o.site_id OR s.account_id<>o.account_id OR s.workspace_id<>o.workspace_id OR s.store_id<>o.store_id OR s.site_id<>o.site_id OR bs.account_id<>o.account_id OR bs.workspace_id<>o.workspace_id OR bs.store_id<>o.store_id`);add('ai-consultant-offers-scope-01416',aiOfferScope.rows[0].bad===0,aiOfferScope.rows[0]);
  const aiOfferTokens=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_ai_consultant_offers WHERE token_hash IS NULL OR length(token_hash)<>64 OR token_hash !~ '^[0-9a-f]{64}$'`);add('ai-consultant-offer-token-hash-01416',aiOfferTokens.rows[0].bad===0,aiOfferTokens.rows[0]);
  const defaults=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_table_fields WHERE default_value='{}'::jsonb`);add('tables-null-default-repair',defaults.rows[0].bad===0,defaults.rows[0]);
  const recordValues=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_table_records r WHERE EXISTS (SELECT 1 FROM jsonb_each(r.values) entry WHERE entry.value='{}'::jsonb)`);add('tables-null-record-repair',recordValues.rows[0].bad===0,recordValues.rows[0]);
  const deployment=await pool.query(`SELECT schema_stage,database_provider,last_migration_at,last_import_at FROM platform_deployment_state WHERE id='primary'`);add('deployment-stage',deployment.rows[0]?.schema_stage==='01094',deployment.rows[0]||null);
  const ok=checks.every(x=>x.ok);console.log(JSON.stringify({ok,stage:'01094',database:db,checks},null,2));if(!ok)process.exitCode=2;
}catch(e){console.error(JSON.stringify({ok:false,stage:'01094',error:e.message,code:e.code||''},null,2));process.exitCode=1;}finally{await pool.end();}
