import {pool,getDatabaseDiagnostics} from '../src/db.mjs';
import {getMigrationStatus01080} from '../src/migration-service.mjs';
const required=['platform_users','platform_accounts','platform_workspaces','platform_stores','platform_memberships','api_sessions','commerce_store_snapshots','commerce_outbox','marketplace_networks','marketplace_categories','marketplace_seller_profiles','marketplace_seller_offers','marketplace_listings','marketplace_carts','marketplace_cart_items','marketplace_orders','marketplace_seller_orders','marketplace_order_items','marketplace_payments','marketplace_payment_allocations','marketplace_inventory_reservations','marketplace_inventory_reservation_items','marketplace_inventory_ledger','marketplace_seller_order_deliveries','marketplace_shipping_events','platform_deployment_state','commerce_store_imports','media_cloud_assets','media_asset_derivatives','media_asset_events','shifttime_tables','shifttime_table_fields','shifttime_table_records','shifttime_table_views','shifttime_table_permissions','shifttime_table_templates','shifttime_schema_migrations'];
const checks=[];function add(name,ok,detail){checks.push({name,ok:Boolean(ok),detail});}
try{
  const db=await getDatabaseDiagnostics();const mig=await getMigrationStatus01080();add('migration-checksums',!mig.some(x=>x.applied&&!x.checksumMatch),mig.filter(x=>x.applied&&!x.checksumMatch).map(x=>x.filename));add('migration-pending',!mig.some(x=>!x.applied),mig.filter(x=>!x.applied).map(x=>x.filename));
  const tables=await pool.query(`SELECT table_name FROM information_schema.tables WHERE table_schema='public'`);const have=new Set(tables.rows.map(x=>x.table_name));add('required-tables',required.every(x=>have.has(x)),required.filter(x=>!have.has(x)));
  const snapshot=await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER (WHERE snapshot->>'schemaId'='shifttime-marketplace-schema-v1')::int valid FROM commerce_store_snapshots`);add('snapshot-schema',snapshot.rows[0].total===snapshot.rows[0].valid,snapshot.rows[0]);
  const scope=await pool.query(`SELECT COUNT(*)::int bad FROM platform_stores st LEFT JOIN platform_workspaces ws ON ws.id=st.workspace_id LEFT JOIN platform_accounts a ON a.id=ws.account_id WHERE ws.id IS NULL OR a.id IS NULL`);add('store-scope-integrity',scope.rows[0].bad===0,scope.rows[0]);
  const seller=await pool.query(`SELECT COUNT(*)::int bad FROM marketplace_seller_profiles sp LEFT JOIN platform_stores st ON st.id=sp.store_id WHERE st.id IS NULL`);add('seller-store-integrity',seller.rows[0].bad===0,seller.rows[0]);
  const order=await pool.query(`SELECT COUNT(*)::int bad FROM marketplace_seller_orders so LEFT JOIN marketplace_orders mo ON mo.id=so.marketplace_order_id LEFT JOIN platform_stores st ON st.id=so.store_id WHERE mo.id IS NULL OR st.id IS NULL`);add('seller-order-scope-integrity',order.rows[0].bad===0,order.rows[0]);
  const media=await pool.query(`SELECT COUNT(*)::int bad FROM media_cloud_assets a LEFT JOIN platform_stores st ON st.id=a.store_id LEFT JOIN platform_workspaces ws ON ws.id=a.workspace_id LEFT JOIN platform_accounts ac ON ac.id=a.account_id WHERE st.id IS NULL OR ws.id IS NULL OR ac.id IS NULL OR st.workspace_id<>a.workspace_id OR ws.account_id<>a.account_id`);add('media-asset-scope-integrity',media.rows[0].bad===0,media.rows[0]);
  const tableScope=await pool.query(`SELECT COUNT(*)::int bad FROM shifttime_tables t LEFT JOIN platform_accounts a ON a.id=t.account_id LEFT JOIN platform_workspaces w ON w.id=t.workspace_id LEFT JOIN platform_stores s ON s.id=t.store_id WHERE (t.scope_type='account' AND a.id IS NULL) OR (t.scope_type='workspace' AND (a.id IS NULL OR w.id IS NULL OR w.account_id<>t.account_id)) OR (t.scope_type='store' AND (a.id IS NULL OR w.id IS NULL OR s.id IS NULL OR w.account_id<>t.account_id OR s.workspace_id<>t.workspace_id))`);add('tables-scope-integrity',tableScope.rows[0].bad===0,tableScope.rows[0]);
  const deployment=await pool.query(`SELECT schema_stage,database_provider,last_migration_at,last_import_at FROM platform_deployment_state WHERE id='primary'`);add('deployment-stage',deployment.rows[0]?.schema_stage==='01092',deployment.rows[0]||null);
  const ok=checks.every(x=>x.ok);console.log(JSON.stringify({ok,stage:'01092',database:db,checks},null,2));if(!ok)process.exitCode=2;
}catch(e){console.error(JSON.stringify({ok:false,stage:'01092',error:e.message,code:e.code||''},null,2));process.exitCode=1;}finally{await pool.end();}
