import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {normalizeNotificationPreferences01417,notificationIsQuietHours01417,notificationPreferenceMode01417,notificationGroupKey01417,notificationFingerprint01417,notificationShouldEscalate01417} from '../src/notification-preferences-core-01417.mjs';
const read=rel=>readFileSync(new URL(`../${rel}`,import.meta.url),'utf8');

test('01417 normalizes preferences with safe defaults',()=>{const p=normalizeNotificationPreferences01417({quietHours:{enabled:true,start:'23:00',end:'07:00'},digest:{intervalMinutes:30},dedupe:{windowMinutes:10},escalation:{enabled:true,roles:['owner','admin'],channels:['email']}});assert.equal(p.quietHours.enabled,true);assert.equal(p.quietHours.timezone,'Europe/Kyiv');assert.equal(p.digest.intervalMinutes,30);assert.equal(p.dedupe.windowMinutes,10);assert.deepEqual(p.escalation.roles,['owner','admin']);});

test('01417 quiet hours defer normal events but critical bypasses',()=>{const prefs=normalizeNotificationPreferences01417({quietHours:{enabled:true,start:'22:00',end:'08:00',timezone:'UTC',criticalBypass:true}});const now=new Date('2026-10-06T23:30:00Z');assert.equal(notificationIsQuietHours01417(prefs,now),true);assert.equal(notificationPreferenceMode01417({preferences:prefs,severity:'high',ruleDelivery:'immediate',now}).mode,'deferred');assert.equal(notificationPreferenceMode01417({preferences:prefs,severity:'critical',ruleDelivery:'digest',now}).reason,'critical_bypass');});

test('01417 digest groups by event type while fingerprint keeps source identity',()=>{const a={type:'supplier.stock.zero',provider:'suppliers',severity:'high',notification:{title:'A',body:'A'},data:{productId:'p1'}},b={...a,notification:{title:'B',body:'B'},data:{productId:'p2'}};assert.equal(notificationGroupKey01417(a,'email','user:u1'),notificationGroupKey01417(b,'email','user:u1'));assert.notEqual(notificationFingerprint01417(a,'email','user:u1'),notificationFingerprint01417(b,'email','user:u1'));});

test('01417 escalation threshold is severity-aware',()=>{const p=normalizeNotificationPreferences01417({escalation:{enabled:true,severityAtLeast:'high',afterMinutes:30}});assert.equal(notificationShouldEscalate01417(p,'medium'),false);assert.equal(notificationShouldEscalate01417(p,'high'),true);assert.equal(notificationShouldEscalate01417(p,'critical'),true);});

test('01417 migration, scheduler, routes and delivery policy are wired',()=>{const migration=read('sql/039_notification_preferences.sql'),server=read('src/server.mjs'),delivery=read('src/notification-delivery-01409.mjs'),service=read('src/notification-preferences-01417.mjs'),config=read('src/config.mjs');assert.match(migration,/shifttime_notification_preferences/);assert.match(migration,/shifttime_notification_digest_queue/);assert.match(migration,/shifttime_notification_escalations/);assert.match(server,/getNotificationPreferences01417/);assert.match(server,/startNotificationPreferencesScheduler01417/);assert.match(delivery,/notificationPolicyForTarget01417/);assert.match(delivery,/scheduleNotificationEscalation01417/);assert.match(service,/processNotificationPreferenceQueue01417/);assert.match(config,/notificationPreferencesPollSeconds/);});
