function bool(v,fallback=false){const x=String(v??'').trim().toLowerCase();if(!x)return fallback;return ['1','true','yes','on'].includes(x);}
function int(v,fallback,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.trunc(n))):fallback;}
function sslMode(v){const x=String(v??'auto').trim().toLowerCase();return ['auto','true','require','false','disable'].includes(x)?x:'auto';}
const nodeEnv=String(process.env.NODE_ENV||'development').trim().toLowerCase()||'development';
export const config=Object.freeze({
  stage:'01094',
  nodeEnv,
  isProduction:nodeEnv==='production',
  host:process.env.HOST||'127.0.0.1',
  port:Number(process.env.PORT||8787),
  databaseUrl:process.env.DATABASE_URL||'',
  databaseSslMode:sslMode(process.env.DATABASE_SSL),
  databasePoolMax:int(process.env.DATABASE_POOL_MAX,10,1,50),
  databaseConnectTimeoutMs:int(process.env.DATABASE_CONNECT_TIMEOUT_MS,10000,1000,120000),
  databaseIdleTimeoutMs:int(process.env.DATABASE_IDLE_TIMEOUT_MS,30000,1000,300000),
  databaseStatementTimeoutMs:int(process.env.DATABASE_STATEMENT_TIMEOUT_MS,30000,1000,300000),
  databaseApplicationName:process.env.DATABASE_APPLICATION_NAME||'shifttime-tables-01094',
  migrationLockTimeoutMs:int(process.env.MIGRATION_LOCK_TIMEOUT_MS,60000,1000,300000),
  productionGuardStrict:bool(process.env.PRODUCTION_GUARD_STRICT,nodeEnv==='production'),
  corsOrigin:process.env.CORS_ORIGIN||'*',
  corsAllowLocalDev:bool(process.env.CORS_ALLOW_LOCAL_DEV,nodeEnv!=='production'),
  devSessionToken:process.env.DEV_SESSION_TOKEN||'change-me-dev-token',
  devUserEmail:process.env.DEV_USER_EMAIL||'owner@local.shifttime',
  devUserName:process.env.DEV_USER_NAME||'ShiftTime Owner',
  marketplaceCommissionRate:Number(process.env.MARKETPLACE_COMMISSION_RATE||8),
  devPaymentSimulation:bool(process.env.DEV_PAYMENT_SIMULATION,true),
  inventoryReservationMinutes:Math.max(1,Math.min(180,Number(process.env.INVENTORY_RESERVATION_MINUTES||15))),
  devInventorySimulation:bool(process.env.DEV_INVENTORY_SIMULATION,true),
  devShippingSimulation:bool(process.env.DEV_SHIPPING_SIMULATION,true),
  mediaStorageProvider:String(process.env.MEDIA_STORAGE_PROVIDER||'disabled').trim().toLowerCase(),
  mediaS3Endpoint:String(process.env.MEDIA_S3_ENDPOINT||'').trim(),
  mediaS3Region:String(process.env.MEDIA_S3_REGION||'auto').trim()||'auto',
  mediaS3Bucket:String(process.env.MEDIA_S3_BUCKET||'').trim(),
  mediaS3AccessKeyId:String(process.env.MEDIA_S3_ACCESS_KEY_ID||'').trim(),
  mediaS3SecretAccessKey:String(process.env.MEDIA_S3_SECRET_ACCESS_KEY||''),
  mediaS3ForcePathStyle:bool(process.env.MEDIA_S3_FORCE_PATH_STYLE,false),
  mediaPublicBaseUrl:String(process.env.MEDIA_PUBLIC_BASE_URL||'').trim().replace(/\/+$/,''),
  mediaUploadUrlTtlSeconds:int(process.env.MEDIA_UPLOAD_URL_TTL_SECONDS,900,60,3600),
  mediaDownloadUrlTtlSeconds:int(process.env.MEDIA_DOWNLOAD_URL_TTL_SECONDS,3600,60,604800),
  mediaMaxUploadBytes:int(process.env.MEDIA_MAX_UPLOAD_BYTES,60*1024*1024,1024,1024*1024*1024),
  bootstrapOwnerEnabled:bool(process.env.BOOTSTRAP_OWNER_ENABLED,false),
  bootstrapOwnerEmail:String(process.env.BOOTSTRAP_OWNER_EMAIL||'').trim(),
  bootstrapOwnerName:String(process.env.BOOTSTRAP_OWNER_NAME||'ShiftTime Owner').trim(),
  bootstrapSessionToken:String(process.env.BOOTSTRAP_SESSION_TOKEN||''),
  bootstrapSessionTtlHours:int(process.env.BOOTSTRAP_SESSION_TTL_HOURS,12,1,24),
  bootstrapAccountId:String(process.env.BOOTSTRAP_ACCOUNT_ID||'acct_default').trim(),
  bootstrapAccountName:String(process.env.BOOTSTRAP_ACCOUNT_NAME||'Моя організація').trim(),
  bootstrapWorkspaceId:String(process.env.BOOTSTRAP_WORKSPACE_ID||'ws_default').trim(),
  bootstrapWorkspaceName:String(process.env.BOOTSTRAP_WORKSPACE_NAME||'Основний Workspace').trim(),
  bootstrapStoreId:String(process.env.BOOTSTRAP_STORE_ID||'store_default').trim(),
  bootstrapStoreName:String(process.env.BOOTSTRAP_STORE_NAME||'Основний магазин').trim()
});
