import {withClient} from './db.mjs';
export async function getAuthorizedPlatformSnapshot(userId,activeScope){return withClient(async client=>{
  const users=await client.query(`SELECT id,email,name,status,created_at "createdAt",updated_at "updatedAt" FROM platform_users WHERE id=$1`,[userId]);
  const accounts=await client.query(`SELECT DISTINCT a.id,a.name,a.slug,a.status,a.owner_user_id "ownerUserId",a.settings,a.created_at "createdAt",a.updated_at "updatedAt" FROM platform_accounts a JOIN platform_memberships m ON m.account_id=a.id AND m.user_id=$1 AND m.status='active' WHERE a.status<>'archived'`,[userId]);
  const workspaces=await client.query(`SELECT DISTINCT w.id,w.account_id "accountId",w.name,w.slug,w.status,w.settings,w.created_at "createdAt",w.updated_at "updatedAt" FROM platform_workspaces w JOIN platform_memberships m ON m.account_id=w.account_id AND m.user_id=$1 AND m.status='active' AND (m.workspace_id IS NULL OR m.workspace_id=w.id) WHERE w.status='active'`,[userId]);
  const stores=await client.query(`SELECT DISTINCT s.id,s.workspace_id "workspaceId",s.name,s.slug,s.status,s.domain,s.locale,s.currency,s.settings,s.created_at "createdAt",s.updated_at "updatedAt" FROM platform_stores s JOIN platform_workspaces w ON w.id=s.workspace_id JOIN platform_memberships m ON m.account_id=w.account_id AND m.user_id=$1 AND m.status='active' AND (m.workspace_id IS NULL OR m.workspace_id=w.id) AND (m.store_id IS NULL OR m.store_id=s.id) WHERE s.status<>'archived'`,[userId]);
  const memberships=await client.query(`SELECT id,user_id "userId",account_id "accountId",workspace_id "workspaceId",store_id "storeId",role,status,permissions,created_at "createdAt",updated_at "updatedAt" FROM platform_memberships WHERE user_id=$1 AND status='active'`,[userId]);
  return {schemaId:'st-marketplace-platform-context',schemaVersion:1,revision:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),users:users.rows,accounts:accounts.rows,workspaces:workspaces.rows,stores:stores.rows,memberships:memberships.rows,activeContext:{userId,accountId:activeScope.accountId,workspaceId:activeScope.workspaceId,storeId:activeScope.storeId},migrations:{legacyCommerceScoped:true},settings:{futureMarketplaceNetwork:true,authMode:'backend-01071'}};
});}

function slugify(v){return String(v??'').trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9а-яіїєґ]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,64)||'item';}
function uid(prefix){return `${prefix}_${crypto.randomUUID().replace(/-/g,'').slice(0,18)}`;}
import crypto from 'node:crypto';
export async function createAuthorizedWorkspace(userId,accountId,input={}){return withClient(async client=>{const auth=await client.query(`SELECT role FROM platform_memberships WHERE user_id=$1 AND account_id=$2 AND status='active' AND workspace_id IS NULL AND store_id IS NULL AND role IN ('owner','admin') LIMIT 1`,[userId,accountId]);if(!auth.rowCount)throw Object.assign(new Error('Account owner/admin permission required'),{statusCode:403});const wsId=uid('ws'),storeId=uid('store'),name=String(input.name||'Workspace').trim(),slug=slugify(input.slug||name);await client.query('BEGIN');try{await client.query(`INSERT INTO platform_workspaces(id,account_id,name,slug,status) VALUES($1,$2,$3,$4,'active')`,[wsId,accountId,name,slug]);await client.query(`INSERT INTO platform_stores(id,workspace_id,name,slug,status,locale,currency) VALUES($1,$2,$3,'store','active',$4,$5)`,[storeId,wsId,`${name} · Магазин`,String(input.locale||'uk-UA'),String(input.currency||'UAH')]);await client.query(`INSERT INTO platform_memberships(id,user_id,account_id,workspace_id,role,status,permissions) VALUES($1,$2,$3,$4,'owner','active','[]'::jsonb)`,[uid('member'),userId,accountId,wsId]);await client.query('COMMIT');return {id:wsId,accountId,name,slug,defaultStoreId:storeId};}catch(e){try{await client.query('ROLLBACK');}catch{}throw e;}});}
export async function createAuthorizedStore(userId,workspaceId,input={}){return withClient(async client=>{const q=await client.query(`SELECT w.account_id FROM platform_workspaces w JOIN platform_memberships m ON m.user_id=$1 AND m.account_id=w.account_id AND m.status='active' AND m.role IN ('owner','admin') AND (m.workspace_id IS NULL OR m.workspace_id=w.id) AND m.store_id IS NULL WHERE w.id=$2 AND w.status='active' LIMIT 1`,[userId,workspaceId]);if(!q.rowCount)throw Object.assign(new Error('Workspace owner/admin permission required'),{statusCode:403});const accountId=q.rows[0].account_id,id=uid('store'),name=String(input.name||'Store').trim(),slug=slugify(input.slug||name);await client.query('BEGIN');try{await client.query(`INSERT INTO platform_stores(id,workspace_id,name,slug,status,domain,locale,currency) VALUES($1,$2,$3,$4,'active',$5,$6,$7)`,[id,workspaceId,name,slug,String(input.domain||''),String(input.locale||'uk-UA'),String(input.currency||'UAH')]);await client.query(`INSERT INTO platform_memberships(id,user_id,account_id,workspace_id,store_id,role,status,permissions) VALUES($1,$2,$3,$4,$5,'owner','active','[]'::jsonb)`,[uid('member'),userId,accountId,workspaceId,id]);await client.query('COMMIT');return {id,workspaceId,name,slug};}catch(e){try{await client.query('ROLLBACK');}catch{}throw e;}});}
